---
title: "GallatinWildlife"
author: "Delores Chan"
date: "2024-01-22"
output: html_document
---

```{r setup, include=TRUE, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(tidytext)
library(textdata)
library(pdftools)
library(ggwordcloud)
library(dplyr)

```


```{r}
## This is the comment letter written by Gallatin Wildlife Association in regard to the NOI for an updated bison and elk management plan. 

## Read in pdf

gallatin_wildlife <- pdf_text(here("NER PDFs", "Gallatin_Wildlife_Association.pdf"))

#gallatin_p2 <- gallatinwildlife[2]
#gallatin_p2
```


```{r}
## Extract lines
gallatin_lines <- data.frame(gallatin_wildlife) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(gallatin_wildlife, pattern = '\\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_squish(text_full))

gallatin_lines
```


```{r}
### Tidy by pages

gallatin_pg <- gallatin_lines %>% 
  slice(-(1:19))
```


```{r}
## Word count by pages
gallatin_words <- gallatin_pg %>% 
  unnest_tokens(word, text_full) %>% 
  select(-gallatin_wildlife)

gallatin_wordcount <- gallatin_words %>% 
  count(page, word)
```


```{r}
### Remove stop words

gallatin_words_clean <- gallatin_words %>% 
  anti_join(stop_words, by = 'word')

gallatin_nonstop_counts <- gallatin_words_clean %>% 
  count(page, word)
```


```{r}
## Top 10 words on Page 1
gallatin_top_10_words <- gallatin_nonstop_counts %>%
  filter(page == 2) %>% 
  arrange(-n) %>% 
  slice(1:10)


ggplot(data = gallatin_top_10_words, aes(x = n, y = reorder(word, -n))) +
  geom_col(fill = "green4") +
  labs(x = "Count", y = "Word", title = "Top 10 Most Frequently Used Words in Page 2")
```

```{r}
## Top 10 words in the whole letter
gallatin_top_10_words_total <- gallatin_nonstop_counts %>% 
  group_by(word) %>%
  summarize(n = sum(n))

gallatin_unique_top_10_words <- gallatin_top_10_words_total %>%
  group_by(word) %>%
  summarize(n = sum(n)) %>%
  slice_max(order_by = n, n = 10)

ggplot(data = gallatin_unique_top_10_words, aes(x = n, y = fct_reorder(word, n))) +
  geom_col(fill = "darkslategray") +
  labs(x = "Count", y = "Word", title = "Top 10 Most Frequently Used Words")
```


```{r}
## Sentiment Analysis for the whole letter

#nrc_lex <- get_sentiments(lexicon = "nrc")

gallatin_nrc <- gallatin_words_clean %>% 
  inner_join(get_sentiments("nrc"))

gallatin_nrc_counts <- gallatin_nrc %>% 
  count(sentiment)

ggplot(data = gallatin_nrc_counts, aes(x = n, y = reorder(sentiment, -n), fill = sentiment))+
  scale_fill_manual(values=c("anticipation" = "green4",
                             "joy" = "green4",
                             "positive" = "green4",
                             "trust" = "green4",
                             "surprise" = "green4",
                             "sadness" = "darkslategray",
                             "disgust" = "darkslategray",
                             "anger" = "darkslategray",
                             "negative" = "darkslategray",
                             "fear" = "darkslategray"))+
  geom_col()+
  labs(x = "Count", y = "Sentiment", title = "Sentiment Analysis")+
  theme_minimal()+
  theme(legend.position = "none")
```